---
- name: Install MySQL and create config file
  hosts: your_client_machine
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is running and enabled
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL configuration file
      template:
        src: mysql.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysql.cnf
        owner: root
        group: root
        mode: '0644'
      notify: Restart MySQL

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

